### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by NewTheHedgefox** [NewDEV-github/Foxy-Adventure#60]
Hello whoever sees this, could someone from the dev team delete my character (named New The Fox) from the game? The thing that earlier you had permission to use my character as a character in game doesn't mean that if I lose contact with the team they still can use my character like nothing ever happened. I really don't want to need to do everything so that you delete him, so right now I'm just asking. Just please, delete my boy named New The Fox from the game.

Regards,
NewTF/NewTHF/Infev

**Comment by JezSonic** [comment]
Ok
